name: read
on: workflow_dispatch
jobs:
 read:
  runs-on: Linux
  steps:
  - name: checkout repo
    uses: actions/checkout@v3

  - name: read
    run: |
     > test.txt
     echo " name : ${{ secrets.name }} " > test.txt
     echo " age : ${{ secrets.age }} " >> test.txt
     echo " email : ${{ secrets.email }}" >> test.txt
