name: read
on: workflow_dispatch
jobs:
 read:
  runs-on: Linux
  steps:
  - name: checkout repo
    uses: actions/checkout@v3

  - name: read
    run: |
     > test.txt
     echo " team : ${{ secrets.team }} " > test.txt
     echo " count : ${{ secrets.count }} " >> test.txt
     echo " city : ${{ secrets.city }}" >> test.txt
